[package]
name = "rust"
version = "0.1.0"
authors = ["Maxim Vasilev <Maxim.Vasilev@jetbrains.com>"]
edition = "2018"

[lib]
name = "enry"
path = "src/lib.rs"

[[bin]]
name = "enry-test"
path = "src/test.rs"
