on: [ push, pull_request ]
name: Tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        rust-version: [stable]
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run tests
        run: cargo test
